### ISSUE TITLE
Lib is not imported after refresh cn1 libs in Codenameone

### ISSUE THREAD

**Issue by DurankGts** [jsfan3/CN1Libs-VideoOptimizer#1]
Please tell me why this lib is not imported after refresh cn1 libs in codenameone

**Comment by jsfan3** [comment]
Thank you for your interest in this CN1Lib and for your report.

I've just tried to import this CN1Lib on two new projects and in both of them the CN1Lib is not imported correctly. There is a 404 error, as in the screenshot below. Clicking on "Retry" doesn't solve the issue, the error remains. If I tap on "Cancel", it seems to success, but it's a false positive feedback. The build hints included in the CN1Lib are not added and the CN1Lib is not usable.

A valid test to see if the CN1Lib is imported is the following line:
`VideoOptimizer videoOptimizer = new VideoOptimizer();`

Because there is a server error, I'm going to report this bug on the Codename One Github issues page.

![404](https://user-images.githubusercontent.com/1997316/67404057-131b0600-f5b3-11e9-8ba2-30ac87fe298f.png)

**Comment by jsfan3** [comment]
I sent a PR with the missing file, this should fix the issue soon.

**Comment by jsfan3** [comment]
This issue is now solved.
