### ISSUE TITLE
please add a feature to check if that lib support arm64

### ISSUE THREAD

**Issue by DurankGts** [jsfan3/CN1Libs-VideoOptimizer#2]
When I compiled my app with this library, the android system don't let me to install it.

Tested in 
model:alcatel 5099A
Os: android 8.0
CPU: ARMv7

when I removed this lib my app it was installed success

**Comment by jsfan3** [comment]
Ok, thank you for the report.

I compiled mobileffmpeg with the options —disable-arm-v7a --disable-arm-v7a-neon, because I supposed that these cpus are not more in the market. I compiled it only for Arm64, but Armv7 is a 32bit cpu (correct me if I’m wrong).

I’ll make soon a new version of this cn1lib that supports also armv7, probably tomorrow.

**Comment by jsfan3** [comment]
Starting from now, the CN1Lib update is available. Open the "Extensions" window, click on update and then refresh cn1lib files.

Let me known if this update solves your issue.
